[2024-05-17T17:18:52.592+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-17T17:18:56.375+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: reddit_etl_pipeline.extract_reddit manual__2024-05-17T17:18:11.425032+00:00 [queued]>
[2024-05-17T17:18:56.433+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: reddit_etl_pipeline.extract_reddit manual__2024-05-17T17:18:11.425032+00:00 [queued]>
[2024-05-17T17:18:56.437+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-05-17T17:18:56.459+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): extract_reddit> on 2024-05-17 17:18:11.425032+00:00
[2024-05-17T17:18:56.467+0000] {standard_task_runner.py:63} INFO - Started process 46 to run task
[2024-05-17T17:18:56.472+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'reddit_etl_pipeline', 'extract_reddit', 'manual__2024-05-17T17:18:11.425032+00:00', '--job-id', '10', '--raw', '--subdir', 'DAGS_FOLDER/reddit_dag.py', '--cfg-path', '/tmp/tmpsvnudq4g']
[2024-05-17T17:18:56.477+0000] {standard_task_runner.py:91} INFO - Job 10: Subtask extract_reddit
[2024-05-17T17:18:56.601+0000] {warnings.py:109} WARNING - /home/airflow/.local/lib/python3.9/site-packages/airflow/settings.py:195: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  SQL_ALCHEMY_CONN = conf.get("database", "SQL_ALCHEMY_CONN")

[2024-05-17T17:19:03.613+0000] {task_command.py:426} INFO - Running <TaskInstance: reddit_etl_pipeline.extract_reddit manual__2024-05-17T17:18:11.425032+00:00 [running]> on host 3b0b4ff62197
[2024-05-17T17:19:22.956+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='reddit_etl_pipeline' AIRFLOW_CTX_TASK_ID='extract_reddit' AIRFLOW_CTX_EXECUTION_DATE='2024-05-17T17:18:11.425032+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-05-17T17:18:11.425032+00:00'
[2024-05-17T17:19:24.459+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-17T17:19:25.226+0000] {logging_mixin.py:188} INFO - Connected to Reddit API successfully!
[2024-05-17T17:19:33.248+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-17T17:19:33.256+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/pipelines/extract_reddit_pipeline.py", line 21, in extract_reddit_pipeline
    file_path = f"{OUTPUT_PATH}/{file_name}.csv"
  File "/opt/airflow/etls/reddit_etl.py", line 51, in load_data_to_csv
    df.to_csv(path, index=False)
  File "/home/airflow/.local/lib/python3.9/site-packages/pandas/util/_decorators.py", line 333, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/pandas/core/generic.py", line 3967, in to_csv
    return DataFrameRenderer(formatter).to_csv(
  File "/home/airflow/.local/lib/python3.9/site-packages/pandas/io/formats/format.py", line 1014, in to_csv
    csv_formatter.save()
  File "/home/airflow/.local/lib/python3.9/site-packages/pandas/io/formats/csvs.py", line 251, in save
    with get_handle(
  File "/home/airflow/.local/lib/python3.9/site-packages/pandas/io/common.py", line 873, in get_handle
    handle = open(
IsADirectoryError: [Errno 21] Is a directory: '/opt/airflow/data/output'
[2024-05-17T17:19:33.466+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=reddit_etl_pipeline, task_id=extract_reddit, run_id=manual__2024-05-17T17:18:11.425032+00:00, execution_date=20240517T171811, start_date=20240517T171856, end_date=20240517T171933
[2024-05-17T17:19:33.541+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 10 for task extract_reddit ([Errno 21] Is a directory: '/opt/airflow/data/output'; 46)
[2024-05-17T17:19:33.591+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-05-17T17:19:33.632+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-05-17T17:19:33.635+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
